# Generated by Django 4.2.6 on 2024-01-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardbookmark',
            name='mark_check',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='mark_check',
        ),
        migrations.RemoveField(
            model_name='resumebookmark',
            name='mark_check',
        ),
    ]
