# Generated by Django 4.2.6 on 2023-12-29 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_board_writer_alter_comment_board_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0005_alter_resume_author'),
        ('post', '0008_alter_post_datetime_alter_post_deadline_and_more'),
        ('bookmarks', '0002_rename_bookmark_postbookmark_resumebookmark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardbookmark',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postbookmark',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='resumebookmark',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='boardbookmark',
            unique_together={('author', 'board')},
        ),
        migrations.AlterUniqueTogether(
            name='postbookmark',
            unique_together={('author', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='resumebookmark',
            unique_together={('author', 'resume')},
        ),
    ]
