# Generated by Django 4.2.6 on 2024-01-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_mark',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
