# Generated by Django 4.2.6 on 2023-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='concert_type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default='type'),
        ),
    ]
