# Generated by Django 4.2.6 on 2023-12-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_images_remove_post_image_alter_wishtype_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
