# Generated by Django 4.2.6 on 2023-12-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_image_img_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
    ]
