# Generated by Django 4.2.6 on 2024-01-09 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_check_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='check_mark',
        ),
        migrations.AddField(
            model_name='post',
            name='check_mark',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
