# Generated by Django 4.2.6 on 2023-12-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_concert_type_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wishtype',
            field=models.TextField(default='type'),
        ),
        migrations.DeleteModel(
            name='wishtype',
        ),
    ]
