# Generated by Django 4.2.6 on 2024-01-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_check_mark_post_check_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='check_mark',
        ),
    ]
