# Generated by Django 4.2.6 on 2023-12-19 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0003_rename_images_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="Image_author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_post",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishtype",
            name="WishType_author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishtype_post",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
