# Generated by Django 4.2.6 on 2023-12-19 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_image_image_author_wishtype_wishtype_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="Image_author",
        ),
        migrations.RemoveField(
            model_name="wishtype",
            name="WishType_author",
        ),
    ]
