# Generated by Django 4.2.6 on 2023-11-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_favorite_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_Post',
        ),
    ]
