# Generated by Django 4.2.6 on 2023-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='post/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduce',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.TextField(default='type', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='wishtype',
            field=models.TextField(default='type', null=True),
        ),
    ]
