# Generated by Django 4.2.6 on 2023-12-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainimage',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='otherimages1',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='otherimages2',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='otherimages3',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='otherimages4',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
