# Generated by Django 4.2.6 on 2023-12-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_mainimage_post_otherimages1_post_otherimages2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mainimage',
            field=models.FileField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='otherimages1',
            field=models.FileField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='otherimages2',
            field=models.FileField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='otherimages3',
            field=models.FileField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='otherimages4',
            field=models.FileField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.TextField(blank=True, default='type', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='wishtype',
            field=models.TextField(blank=True, default='type', null=True),
        ),
    ]
