# Generated by Django 4.2.7 on 2023-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('award', models.TextField()),
                ('introduce', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resumes/photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
