# Generated by Django 4.2.6 on 2023-12-26 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='careers',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='regions',
        ),
        migrations.AddField(
            model_name='image',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='consumer.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='consumer.resume'),
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='consumer.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='consumer.resume'),
        ),
        migrations.AlterField(
            model_name='region',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='consumer.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
