# Generated by Django 5.0 on 2023-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(upload_to='image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photos',
            field=models.FileField(blank=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
