# Generated by Django 4.2.6 on 2023-10-27 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0002_consumers_delete_consumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumers',
            new_name='consumer',
        ),
    ]
