# Generated by Django 4.2.6 on 2023-12-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_remove_resume_awards_remove_resume_careers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='consumer.resume'),
        ),
    ]
