# Generated by Django 4.2.6 on 2023-12-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_alter_image_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='mainimage',
            field=models.FileField(blank=True, null=True, upload_to='image/resume/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='otherimages1',
            field=models.FileField(blank=True, null=True, upload_to='image/resume/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='otherimages2',
            field=models.FileField(blank=True, null=True, upload_to='image/resume/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='otherimages3',
            field=models.FileField(blank=True, null=True, upload_to='image/resume/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='otherimages4',
            field=models.FileField(blank=True, null=True, upload_to='image/resume/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
