# Generated by Django 4.2.6 on 2023-12-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='registered_date',
            new_name='created_date',
        ),
    ]
