# Generated by Django 4.2.7 on 2023-11-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_board_delete_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'community', 'verbose_name_plural': 'community'},
        ),
    ]
