# Generated by Django 4.2.6 on 2023-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_board_writer_alter_comment_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='writer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='author',
        ),
    ]
