# Generated by Django 4.2.7 on 2023-12-13 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_comment_alter_board_options_remove_board_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(related_name='liked_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
