# Generated by Django 4.2.6 on 2023-12-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='photoURL',
        ),
    ]
