# Generated by Django 4.2.6 on 2023-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Uidd',
            field=models.TextField(default='Uidd', primary_key=True, serialize=False, unique=True),
        ),
    ]
