# Generated by Django 4.2.6 on 2023-11-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_posts',
        ),
    ]
