# Generated by Django 4.2.6 on 2023-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_bookmarked_users_alter_post_author'),
        ('accounts', '0004_user_bookmarked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_posts',
            field=models.ManyToManyField(null=True, related_name='bookmarked_by_users', to='post.post'),
        ),
    ]
