# Generated by Django 4.2.6 on 2023-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_bookmarked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_posts',
        ),
    ]
