# Generated by Django 4.2.6 on 2023-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retouch_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
