# Generated by Django 4.2.6 on 2024-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='messagebody',
            field=models.TextField(null=True),
        ),
    ]
