# Generated by Django 4.2.6 on 2024-01-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('message_token', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='board',
        ),
        migrations.AddField(
            model_name='notification',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.board'),
        ),
    ]
